apiVersion: v1
kind: Service
metadata:
  name: iga-redis
  namespace: iga
  labels:
    app.kubernetes.io/name: iga-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: iga-platform
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: iga-redis
    app.kubernetes.io/component: cache
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: metrics
      protocol: TCP
      port: 9121
      targetPort: 9121
  sessionAffinity: None
